var annotated_dup =
[
    [ "BetCity", "namespace_bet_city.html", [
      [ "Storage", "namespace_bet_city_1_1_storage.html", [
        [ "ISubmitArchive&lt; T &gt;", "interface_bet_city_1_1_storage_1_1_i_submit_archive-1-g.html", "interface_bet_city_1_1_storage_1_1_i_submit_archive-1-g" ],
        [ "IModifyArchive", "interface_bet_city_1_1_storage_1_1_i_modify_archive.html", "interface_bet_city_1_1_storage_1_1_i_modify_archive" ],
        [ "ArchiveContainer", "class_bet_city_1_1_storage_1_1_archive_container.html", "class_bet_city_1_1_storage_1_1_archive_container" ],
        [ "OwnedSouvenirDTO", "class_bet_city_1_1_storage_1_1_owned_souvenir_d_t_o.html", "class_bet_city_1_1_storage_1_1_owned_souvenir_d_t_o" ],
        [ "StorageManager", "class_bet_city_1_1_storage_1_1_storage_manager.html", "class_bet_city_1_1_storage_1_1_storage_manager" ]
      ] ]
    ] ],
    [ "BagData", "class_bag_data.html", null ],
    [ "BattleCard", "class_battle_card.html", null ],
    [ "BattleDeckManager", "class_battle_deck_manager.html", null ],
    [ "Block", "class_block.html", null ],
    [ "Card", "class_card.html", null ],
    [ "CardCounter", "class_card_counter.html", null ],
    [ "CardDisplay", "class_card_display.html", null ],
    [ "CardStore", "class_card_store.html", null ],
    [ "ClickCard", "class_click_card.html", null ],
    [ "CoinManager", "class_coin_manager.html", null ],
    [ "CombatManager", "class_combat_manager.html", "class_combat_manager" ],
    [ "D4DiceManager", "class_d4_dice_manager.html", null ],
    [ "DeckManager", "class_deck_manager.html", null ],
    [ "DialogManager", "class_dialog_manager.html", null ],
    [ "DiceCounter", "class_dice_counter.html", null ],
    [ "DiceManager", "class_dice_manager.html", null ],
    [ "EconomySystem", "class_economy_system.html", "class_economy_system" ],
    [ "EventSceneController", "class_event_scene_controller.html", null ],
    [ "EventWindowManager", "class_event_window_manager.html", null ],
    [ "GameDataManager", "class_game_data_manager.html", "class_game_data_manager" ],
    [ "GraveyardManager", "class_graveyard_manager.html", "class_graveyard_manager" ],
    [ "HighlightOnSelect", "class_highlight_on_select.html", null ],
    [ "IModifySouvenir", "interface_i_modify_souvenir.html", null ],
    [ "InventoryData", "class_inventory_data.html", null ],
    [ "InventoryDisplay", "class_inventory_display.html", null ],
    [ "InventoryManager", "class_inventory_manager.html", "class_inventory_manager" ],
    [ "Item", "class_item.html", null ],
    [ "ItemPopupManager", "class_item_popup_manager.html", null ],
    [ "MonoSingleton&lt; T &gt;", "class_mono_singleton-1-g.html", null ],
    [ "MonsterCard", "class_monster_card.html", null ],
    [ "MySceneLoader", "class_my_scene_loader.html", null ],
    [ "NewBehaviourScript", "class_new_behaviour_script.html", null ],
    [ "Node", "class_node.html", null ],
    [ "Open", "class_open.html", null ],
    [ "PhaseDisplayer", "class_phase_displayer.html", null ],
    [ "PlayerAction", "class_player_action.html", null ],
    [ "PlayerController", "class_player_controller.html", null ],
    [ "PlayerData", "class_player_data.html", null ],
    [ "PlayerEventSystem", "class_player_event_system.html", null ],
    [ "PlayerMovement", "class_player_movement.html", null ],
    [ "PlayerState", "class_player_state.html", null ],
    [ "PlayerStateSaver", "class_player_state_saver.html", null ],
    [ "PopupController", "class_popup_controller.html", "class_popup_controller" ],
    [ "ReturnManager", "class_return_manager.html", null ],
    [ "SanityEvent", "class_sanity_event.html", null ],
    [ "SanityManager", "class_sanity_manager.html", null ],
    [ "SanityUIController", "class_sanity_u_i_controller.html", null ],
    [ "SceneStateManager", "class_scene_state_manager.html", null ],
    [ "Souvenir", "class_souvenir.html", "class_souvenir" ],
    [ "SouvenirData", "class_souvenir_data.html", "class_souvenir_data" ],
    [ "SouvenirDataManager", "class_souvenir_data_manager.html", "class_souvenir_data_manager" ],
    [ "SouvenirManager", "class_souvenir_manager.html", "class_souvenir_manager" ],
    [ "SpellCard", "class_spell_card.html", null ],
    [ "StoreManager", "class_store_manager.html", null ],
    [ "Test", "class_test.html", null ]
];